export default [
  {
    date: '2026-08-07',
    month: 'Aug',
    day: '07',
    weekday: 'Friday',
    title: 'Speed Racer',
    year: '2008',
    tmdbId: '7459-speed-racer',
    poster: 'fxRIpx9Op9h71q3tvuabx4GryyP.jpg',
    postponed: true,
  },
  {
    date: '2026-08-21',
    month: 'Aug',
    day: '21',
    weekday: 'Friday',
    title: 'Stuart Little',
    year: '1999',
    tmdbId: '10137-stuart-little',
    poster: '362lcwTJlNyAhitTlp2UraECISR.jpg',
  },
  {
    date: '2026-09-11',
    month: 'Sep',
    day: '11',
    weekday: 'Friday',
    title: 'Back to the Future Part II',
    year: '1989',
    tmdbId: '165-back-to-the-future-part-ii',
    poster: 'YBawEsTkUZBDajKbd5LiHkmMGf.jpg',
  },
  {
    date: '2026-09-12',
    month: 'Sep',
    day: '12',
    weekday: 'Saturday',
    title: 'Back to the Future Part III',
    year: '1990',
    tmdbId: '196-back-to-the-future-part-iii',
    poster: 'crzoVQnMzIrRfHtQw0tLBirNfVg.jpg',
  },
  {
    date: '2026-10-02',
    month: 'Oct',
    day: '02',
    weekday: 'Friday',
    title: 'Ghostbusters',
    year: '1984',
    tmdbId: '620-ghostbusters',
    poster: '7E8nLijS9AwwUEPu2oFYOVKhdFA.jpg',
  },
  {
    date: '2026-10-16',
    month: 'Oct',
    day: '16',
    weekday: 'Friday',
    title: 'Coraline',
    year: '2009',
    tmdbId: '14836-coraline',
    poster: '4jeFXQYytChdZYE9JYO7Un87IlW.jpg',
  },
  {
    date: '2026-10-30',
    month: 'Oct',
    day: '30',
    weekday: 'Friday',
    title: 'Haunted Mansion',
    year: '2023',
    tmdbId: '616747-haunted-mansion',
    poster: '8Im6DknDVxRiGXc5t8rVOJyzuNx.jpg',
  },
  {
    date: '2026-11-06',
    month: 'Nov',
    day: '06',
    weekday: 'Friday',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: '2001',
    tmdbId: '120-the-lord-of-the-rings-the-fellowship-of-the-ring',
    poster: '6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
  },
  {
    date: '2026-11-07',
    month: 'Nov',
    day: '07',
    weekday: 'Saturday',
    title: 'The Lord of the Rings: The Two Towers',
    year: '2002',
    tmdbId: '121-the-lord-of-the-rings-the-two-towers',
    poster: '5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
  },
  {
    date: '2026-11-13',
    month: 'Nov',
    day: '13',
    weekday: 'Friday',
    title: 'The Lord of the Rings: The Return of the King',
    year: '2003',
    tmdbId: '122-the-lord-of-the-rings-the-return-of-the-king',
    poster: 'rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  },
];
